name: publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
    name: docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      - name: Install dependencies 
        run: yarn install

      - name: Build 
        run: yarn build  

      - name: Generate docs
        run: yarn doc
  
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./doc